# Generated by Django 5.0.7 on 2024-09-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0008_evento_compraentrada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descripcion',
        ),
    ]
